[package]
name = "creator"
version = "0.4.1"
edition = "2018"
authors = ["enfipy <enfipy@gmail.com>", "olvyko <olvyko@gmail.com>"]
description = "Mobile Game Framework"
repository = "https://github.com/creator-rs/creator"
license = "Apache-2.0"
keywords = ["build", "android", "apple", "ios", "tools"]
readme = "README.md"
exclude = [".github/**/*"]

[dependencies]
creator-derive = { path = "crates/creator-derive", version = "0.4.1" }

creator-ads = { path = "crates/creator-ads", version = "0.4.1", optional = true }
creator-tools = { path = "crates/creator-tools", version = "0.4.1", optional = true }
creator-permissions = { path = "crates/creator-permissions", version = "0.4.1", optional = true }

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = "0.2"

[patch.crates-io]
cpal = { git = "https://github.com/creator-rs/cpal", branch = "mike-ios" }

[features]
default = []

[workspace]
members = [
    "crates/*",
    "examples/*",
]
